database: {
  postgres: {
    driver_name: "postgres",
    username: "docker",
    password: "qwe12345",
    db_name: "request_proxy",
    ssl_mode: "disable",
    host: "localhost",
    max_conn: 10,
  }
}

web: {
  server: {
    address: "0.0.0.0",
    port: "5000",
    host: "example.com",
    protocol: "http",
  }
}

proxy: {
  server: {
    address: "0.0.0.0",
    port: "5005",
    host: "example.com",
    protocol: "http",
  }
}

logger: {
  gin_file:  "/var/log/proxybuster/gin.log",
  gin_level: "release",  # (release|test|debug)
  common_file: "/var/log/proxybuster/common.log",
  common_level: "debug",  # (panic|fatal|error|warn|info|debug|trace)
  stdout_log: "true",
}